mozilla/ssl-config-generator

- src/templates/index.ejs
> official branding "moz://a" is lowercase

- src/templates/partials/postfix.hbs
I haven't tested this, but I think both should say ciphers. It currently generates "tls_medium_cipherlist=" (empty) which postfix doesn't accept.
Also, I don't see the postfix source calling `SSL*_set_ciphersuites`, so I guess they don't support specifying 1.3 ciphersuites (only ciphers of TLS1.2 and below.)
> fix postfix template - ciphers vs ciphersuites

- src/js/configs.js
- src/templates/partials/traefik.hbs
These commits add support for the new Traefik v2 configuration format. Starting
with Traefik 2.0, there are now two parts of a Traefik configuration, static
and dynamic configuration. This means the configuration format changed
considerably from a relatively simple format to something more complex.
In `config.js`, updated the latest version of Traefik. In `traefik.hbs`, added
the complete template for the new configuration format, as found in the Traefik
documentation. Especially relevant are the following documentation sections:
- [ TLS Configuration Is Now Dynamic, per Router ]
https://docs.traefik.io/migration/v1-to-v2/#tls-configuration-is-now-dynamic-per-router
- [ HTTP to HTTPS Redirection Is Now Configured on Routers ]
https://docs.traefik.io/migration/v1-to-v2/#http-to-https-redire …
> Support for Traefik v2

- src/templates/partials/awsalb.hbs
The previous URL linked to security policies for Classic Load Balancers, however, this file is about Application Load Balancers.
> Fix link to AWS ALB security policies

- src/templates/partials/awsalb.hbs
Updates the Intermediate configuration for Amazon Web Services’s Application Load Balancer to `ELBSecurityPolicy-FS-1-2-Res-2019-08` [which was added on October 8, 2019](https://aws.amazon.com/about-aws/whats-new/2019/10/application-load-balancer-and-network-load-balancer-add-new-security-policies-for-forward-secrecy-with-more-strigent-protocols-and-ciphers/).
This policy is the same as the previous `ELBSecurityPolicy-TLS-1-2-2017-01` but removes support for AES128-GCM-SHA256, AES128-SHA256, AES256-GCM-SHA384, and AES256-SHA256.
Here’s a table comparing the TLS 1.2 cipher suites of the [Intermediate configuration](https://wiki.mozilla.org/Security/Server_Side_TLS#Intermediate_compatibility_.28recommended.29), the previous `ELBSecurityPolicy-TLS-1-2-2017-01` security policy, and the new …
> Update Intermediate security policy for AWS ALB

- src/js/configs.js
- src/templates/partials/lighttpd.hbs
simplify lighttpd config
* latest version is lighttpd 1.4.55  (how does docs/39dd7eed14622039aa44.index.js get updated?)
* lighttpd 1.4.50 and later has simpler (and more efficient) syntax for http to https redirect
* `protocol = "https://"` is not use by lighttpd.conf and gets ignored
* `ssl.disable-client-renegotiation = "enable"` is the default, and always has been for that config option.
* `setenv.add-environment = ( "HTTPS" => "on" )` is unnecessary, as lighttpd already does this for backends when the connection uses https.
Greetings from a lighttpd developer. :)
> simplify lighttpd config

- src/templates/partials/postgresql.hbs
PostgreSQL version 12 added a new ssl_min_protocol_version configuration
option to control the SSL versions the server uses.
When testing I also discovered that PostgreSQL rejects an empty
ssl_ciphers value, so I've wrapped this in an if to prevent it being
output if ciphers is empty (modern profile).
> Updating PostgreSQL template for version 12

- src/js/configs.js
- src/templates/partials/redis.hbs
Adding Redis 6.0 support. Please do not merge yet. This version is in release candidate and is not officially GA. If there are any material changes I will update this PR. I'll let you know when released.
> Adding Redis 6.0 Support

- src/templates/partials/redis.hbs
The quotation marks around TLS protocols prevent Redis from interpreting each individual protocol as a separate argument and groups all of them together.
> The quotes are important :)

- src/templates/partials/haproxy.hbs
Refer to the configuration manual, the `prefer-client-ciphers` option was first introduced in HAProxy 1.8.
Solve Issue #110
> HAProxy: add `prefer-client-ciphers` option

- src/js/configs.js
Since the fix to allow Dovecot to recognize the option to make use of TLSv1.3 it has not been merged for now, I think we should disable the "modern" configuration since it leads to a non-working config file.
> Use noSupportedVersion since dovecot doesn't support TLSv1.3 for now

- src/js/configs.js
- src/templates/partials/lighttpd.hbs
refresh lighttpd config
* Comment how to listen on multiple sockets, IPv4 and IPv6.
* Disable Session Tickets.
* Add warnings for using old versions of OpenSSL.
* Use separate blocks to redirect from http to https, and to set Strict-Transport-Security response header. (reduce duplication of config directives)
These changes prepare for the upcoming release of lighttpd 1.4.56, which will be submitted in a separate pull request, once lighttpd 1.4.56 is released in the next month or so.
> lighttpd updates

- src/templates/partials/nginx.hbs
This fixes #95.
I have tested the config in an nginx/1.14.2 on Debian. 
I have not checked if the code still builds, but I don't see, how modifying a template this way, would influence this.
Thanks to @runapp for the suggestion.
Greetings Nmxosm
> Nginx: Wrap "return 301" inside a `location` block

- src/js/configs.js
Close #156.
https://doc.dovecot.org/settings/core/#core_setting-ssl_min_protocol
> Dovecot: Add TLS 1.3 support and update latest version.

- src/js/configs.js
- src/templates/partials/squid.hbs
The configuration is done to support Squid >= 3.5 ([The oldest version packaged in common Linux distributions](https://pkgs.org/download/squid))
The generated configuration was tested in the following conditions:
- Tested both "Intermediate" and "Modern" configurations
- Only in the "cache proxy with SSL bump" mode
- Only with Squid 4.14 on Fedora 34
I didn't find exactly what is the first Squid version that support TLS 1.3, so I set it to 3.5 in `configs.js`.
Close #112
> Add Squid support

- src/js/configs.js
lighttpd 1.4.67 version update
Please also review some simple but older PRs: https://github.com/mozilla/ssl-config-generator/pull/137 for Apache and https://github.com/mozilla/ssl-config-generator/pull/139 for lighttpd for them to prefer 308 Permanent Redirect to 301 Moved Permanently
Thank you.
> lighttpd 1.4.67 version update

- src/static/guidelines/5.0.json
I incorrectly fixed this in the `/docs` directory in #200 . It should have been fixed here in `/src`
> Fix incorrect href in 5.0 JSON guideline

- package-lock.json
- package.json
The current version of handlebars (4.7.8) depends on minimist but specifies the vulnerable version (1.2.5).
Until handlebars 5 comes out, we need to set a minimist version manually. After it's out we can remove the dependency on minimist
https://github.com/handlebars-lang/handlebars.js/issues/1851
> Update minimist to 1.2.8

- package-lock.json
- package.json
Until Va1/browser-sync-webpack-plugin#96 is merged browser-sync-webpack-plugin doesn't support browser-sync 3.0.2. This rolls us back to 2.29.3
> Revert browser-sync back to 2.29.3

- src/js/configs.js
There have been more formats in the JSON specs added since, the current description is outdated.
> Update cipherFormat wording

- src/templates/partials/apache.hbs
I haven't found any reference why restrict to 2.4.14+ — bugs were in 2.4.10 and 2.4.11 implementations, good performance is reported since 2.4.13; this updates it accordingly.
> Update Apache stapling version

- src/templates/partials/mysql.hbs
- src/templates/partials/nginx.hbs
- src/templates/partials/proftpd.hbs
- src/templates/partials/redis.hbs
- src/templates/partials/tomcat.hbs
Replaces variety of `each/unless` historic constructs with more readable `join()` helper that was added later where nothing more complex is necessary (mysql, nginx, proftpd, redis, tomcat) mainly to get rid of fighting the separators and wrestling with negative space tricks. (More complex iterations for XML or quotes were left intact.)
_(Tested, no change to output.)_
> Join output protocols

- src/js/index.js
When a server doesn't use OpenSSL, its input should be disabled. This used to work, but got broken in fd14d6f when shortening URLs.
The readonly toggle helps understanding the context at least a bit (a mouseover explainer for disabled inputs would be even better), helping the UI make a little more sense.
https://github.com/mozilla/ssl-config-generator/assets/1784648/853c8e45-2f4e-47e1-94bb-e513cc3860d4
> Fix #openssl-version readonly toggle

- src/templates/partials/oraclehttp.hbs
Enables setting `SSLHonorCipherOrder` per config output to adhere to recommendations.
(This hasn't been updated in oraclehttp since v4 and doesn't match current v5.x specs.)
Adds version test for OHS 12.2.1 according to [KB 1485047.1](https://support.oracle.com/knowledge/Middleware/1485047_1.html)
> Update Oracle serverPreferredOrder

- src/js/configs.js
- src/templates/partials/awsalb.hbs
From this accouncement:
https://aws.amazon.com/about-aws/whats-new/2023/03/application-load-balancer-tls-1-3/ TLSv1.3 support is now generally available in AWS ALB. They have added a new set of security policies that enable TLSv1.3. I have selected the following policies which are the closest fit to the Mozilla server side TLS recommendations:
**Old:**
Remains `TLS-1-0-2015-04`. This policy doesn't support TLSv1.3, but it is the only policy available which supports DES-CBC3-SHA.
**Intermediate:**
Switched from `FS-1-2-Res-2019-08` to `TLS13-1-2-2021-06`. These two policies support the same set of TLSv1.2 ciphers, but the newer one also adds TLSv1.3 support.
**Modern:**
Can be supported now, using `TLS13-1-3-2021-06`.
> Update AWS ALB security policies for 2023.3.22

- src/js/configs.js
- src/templates/partials/nginx.hbs
Disabled in https://github.com/mozilla/server-side-tls/pull/80 (as explained in [archive](https://wiki.mozilla.org/Security/Archive/Server_Side_TLS_4.0#TLS_tickets_.28RFC_5077.29) and in detail https://github.com/mozilla/server-side-tls/issues/135), this can now be left out for nginx:
> "TLS session tickets encryption keys are now automatically rotated when using shared memory in the `ssl_session_cache` directive."
— _https://trac.nginx.org/nginx/milestone/nginx-1.23.2 (https://nginx.org/en/CHANGES-1.24)_
Fixes https://github.com/mozilla/server-side-tls/issues/284, https://github.com/mozilla/server-side-tls/issues/282, and tangentially resolves #69
(Also fixes #239 along the way by updating the versions used…)
> Allow nginx ≥1.23.2 `ssl_session_tickets`

- .github/workflows/test-build.yml
Until preview builds are added here, this at least shows some basic feasibility of package updates and nodejs version compatibility on the webpack build output.
`test-build #1` workflow run e.g. [step:5:350](https://github.com/mozilla/ssl-config-generator/actions/runs/11186792442/job/31102543824#step:5:350)
> Add matrix strategy to test node versions building PRs

- src/static/guidelines/4.0.json
- src/static/guidelines/5.0.json
These files were originally being uploaded to the infosec S3 bucket that's no longer used for the spec JSONs publishing (the source for that was the former repo, before spinning off the tool here) — so this only matches the newer files that already use the current GH.io–hosted deployment, for them to correctly self-reference their location going forward.
_(This only changes the deployed jsons under the current hostname, to reference their location where they are being loaded from; all the pre-existing jsons kept in the statics bucket for posterity will have their href unchanged, and when loaded from the security statics will still reference themselves correctly there.)_
These came in via 1285bc8 but the hrefs were never updated to match.
> Update JSON v4.0–v5.0 specs canonical location

- src/js/configs.js
- src/templates/partials/jetty.hbs
Fixes #154
With any `output.ciphers` present, for TLSv1.3 to work also the `output.cipherSuites` have to be provided for TLSv1.3 handshakes not to fail (i.e. when `IncludeCipherSuites` defined, also the TLSv1.3 compatible suites as defined in RFC 8446 have to be explicitly set, or TLSv1.3-only clients won't be able to connect).
Fixes `intermediate` and `old` configs.
_Support for `*_CHACHA20_POLY1305_*` was added in 11.0.13 [JDK-8140466](https://bugs.openjdk.org/browse/JDK-8140466) but since it was not addressed for TLSv12 suites before, I haven't added anything mentioning the JSSE support for TLSv13 either — if that errors out for someone running older revisions, feel free to open separate issue for that; however we're not comparing such versions in the logic here, so it may only warrant …
> Fix Jetty `intermediate`/`old` configs for TLSv1.3-only clients

- .github/workflows/deploy-to-production.yml
Resolves #161 
Publishes ssl-config-generator to production from master. No underlying git history and/or keeping a separate branch needed, artifacts are built and published straight to the deployment environment.
Compiles under 10sec, whole npm ci takes about ~30sec, all in all builds and deploys under 1 minute.
> Add build & deploy workflow for github-pages environment

- src/js/configs.js
- src/templates/partials/tomcat.hbs
To support not only OpenSSL, but also JSSE fully, whenever ciphers are configured, TLSv1.3 suites must be included, otherwise TLSv1.3–only clients won't be able to connect if not using OpenSSL.
Fixes https://github.com/mozilla/server-side-tls/issues/280
_(similar to #226, but with more possible implementations treating the config different ways)_
The output template doesn't set any Connector details, so the config works for whatever implementation the consumers use (JSSE Java SSL or OpenSSL, depending on tcnative or APR/native lib):
https://tomcat.apache.org/tomcat-9.0-doc/config/http.html#SSL_Support
> The NIO and NIO2 connectors use either the JSSE Java SSL implementation or an OpenSSL implementation, whereas the APR/native connector uses OpenSSL only. Prior to Tomcat 8.5, different …
> Include TLSv1.3 suites in some Tomcat configurations

- src/js/configs.js
OHS uses `mod_ossl` and not `mod_ssl`.
https://docs.oracle.com/en/middleware/fusion-middleware/web-tier/12.2.1.4/administer-ohs/under_mods.html
> **mod_ossl Module**—Enables Cryptography (SSL)
> The mod_ossl module enables strong cryptography for Oracle HTTP Server. It is a plug-in to Oracle HTTP Server that enables the server to use SSL. The functionality of this module is similar to the functionality of Apache’s mod_ssl module. However, the cryptography engine used in the mod_ossl module differs from that of the mod_ssl module. The mod_ossl module uses Oracle’s Secure Socket Layer, which is based on RSA security technology, whereas the mod_ssl module relies on OpenSSL to provide the cryptography engine. […] It uses a version of the underlying SSL libraries that has gone through formal …
> Disable OpenSSL for Oracle HTTP

- src/templates/partials/apache.hbs
Folding two different `SSLProtocol` blocks into one, without any change to the logic in use or the final output.
The only condition targeting Apache 2.3.16 is whether to explicitly exclude SSLv2 or not (as it is disabled by default from that point on), not worth maintaining as separate blocks with different formatting etc.
Any SSLv3 logic is removed as it is no longer present in any configs and is also only disabled completely.
Absolutely no impact to the actual output.
The `2.3.16` condition for explicit SSLv2 removal is just kept within the single block, SSLv3 removal is unconditional.
(Includes some indentation and whitespace control for better readability, but not as "neat" as before; however the deduplication is hopefully worth it.) …
> Simplify protocol logic for Apache

- src/js/configs.js
Only list values that are not the default state for given options.
(Also renders supported clients for stunnel, that ought to be shown.)
> Leave out defaults from config options

- src/templates/partials/dovecot.hbs
Resolves #265
Reverts #175, referencing:
> "Since v2.3.3+ Diffie-Hellman parameters have been made optional, and you are encouraged to disable non-ECC DH algorithms completely."
> — [doc.dovecot.org/configuration_manual/dovecot_ssl_configuration](https://doc.dovecot.org/configuration_manual/dovecot_ssl_configuration/#ssl-security-settings)
The `ssl_dh` config is indeed optional so Dovecot no longer refuses to start without DH params, but we **_do_ need** to configure it for `intermediate` and `old` though.
> Fix Dovecot v2.3.3+ DH config

- src/js/configs.js
- src/templates/partials/apache.hbs
Fixup according to `mod_ssl` docs:
> "Custom DH parameters and an EC curve name for ephemeral keys, can also be added to end of the first file configured using [`SSLCertificateFile`](https://httpd.apache.org/docs/2.4/mod/mod_ssl.html#sslcertificatefile). This is supported in version **2.4.7 or later**."
> Update Apache version for appending dhparam to cert file

- src/js/state.js
Updates to support OpenSSL 3.x
Resolves #188
Tracked in #260
* Set SECLEVEL=0 in cipherstring for `old` output to allow TLSv1–v1.1 for OpenSSL 3.x
* ~Hide DH parameters for servers calling OpenSSL interfaces `SSL_CTX_set_dh_auto()` or `SSL_set_dh_auto()` to use RFC7919.~ (TLS1.2 will keep just ffdhe2048, TLS1.3 will have to limit curves/groups, followup TBD)
- - - - -
TESTING:
https://test-3x--mozsslconf-dev.netlify.app/#openssl=3.3.3&config=old&server=postgresql
> Lower SECLEVEL in `old` config for OpenSSL 3.x compatibility

- src/templates/partials/caddy.hbs
- src/templates/partials/go.hbs
Replace `form.config` in template conditionals
Instead, prefer to check output.protocols in template conditionals.
> Replace config name with feature check in go/caddy conditions

- src/js/configs.js
- src/templates/partials/lighttpd.hbs
Updates lighttpd to 1.4.76
Leaves out explicit settings when server defaults based on its version can be used implicitly.
- lighttpd 1.4.56 and later default to MinProtocol TLSv1.2
- lighttpd 1.4.68 and later default to a strict set of PFS ciphers and to -ServerPreference, since a strict set of PFS ciphers is the default.
- Simplify intermediate and modern configs for lighttpd 1.4.68 and later.
_lighttpd defaults will incrementally be made more secure in the future and using lighttpd secure defaults (without explicitly hard-coding the defaults at a point in time) will allow users to get more secure defaults along with lighttpd upgrades, instead of accidentally continuing to use explicitly set older, less-secure config settings._
Adds future defaults that should be released in lighttpd …
> Use implicit settings for lighttpd ≥1.4.68

- src/js/configs.js
- src/templates/partials/haproxy.hbs
haproxy: prefer ssl-min-ver with haproxy 2.2+
closes: #152
closes: #206
> haproxy: prefer ssl-min-ver with haproxy 2.2+

- src/templates/partials/apache.hbs
apache: avoid double-percent-encode in rewrite
x-ref:
"Apache rewrite config - double-encoding query strings"
https://github.com/mozilla/ssl-config-generator/issues/150
github: closes #150
> apache: avoid double-percent-encode in rewrite

- src/templates/partials/haproxy.hbs
haproxy: ssl-security-level for dhParamSize 1024
x-ref:
https://github.com/mozilla/ssl-config-generator/pull/275#issuecomment-2504932811
github: #275
> haproxy: ssl-security-level for dhParamSize 1024

- README.md
- src/js/configs.js
- src/js/index.js
- src/js/state.js
- src/templates/partials/apache.hbs
- src/templates/partials/nginx.hbs
- src/templates/partials/proftpd.hbs
Version-based supportsOcspStapling
x-ref:
"Change supportsOcspStapling from boolean to version based"
https://github.com/mozilla/ssl-config-generator/issues/138
github: closes #138
> Version-based supportsOcspStapling

- src/templates/partials/nginx.hbs
nginx: wrap server in http context
share most of the ssl config in the http context
> nginx: wrap server in http context

- src/templates/partials/apache.hbs
- src/templates/partials/oraclehttp.hbs
use an explicit list of allowed protocols to avoid having to special-case 'All -SSLv2 -SSLv3' or 'All -SSLv3' depending on version support
x-ref:
Explicitly exclude SSLv3 in older Oracle HTTP versions
https://github.com/mozilla/ssl-config-generator/pull/271
github: closes #271
> apache,oraclehttp: explicit SSLProtocol list

- src/templates/partials/lighttpd.hbs
explicit protocol list for (ancient) openssl 1.0.2
similar to #286, but apache has is own string translation before passing protocol string to openssl interfaces
> lighttpd: explicit protocol list for openssl 1.0.2

- src/js/index.js
- src/templates/index.ejs
use plain javascript to replace jquery
bugfix: avoid repeated calls to state() for single change
x-ref:
https://github.com/mozilla/ssl-config-generator/pull/244
https://github.com/mozilla/ssl-config-generator/pull/283
https://github.com/mozilla/ssl-config-generator/pull/288
> use plain javascript to replace jquery

- src/js/index.js
- src/templates/index.ejs
Revert "use js to replace jquery"
This reverts commit 918ebaace30ce48cf7801655f4e3c140405778d0.
I need to review the policy or find a different mechanism to reset the form upon change in server selection
> Content-Security-Policy: The page’s settings blocked an event handler (script-src-attr) from being executed because it violates the following directive: “script-src 'self' https://www.google-analytics.com/analytics.js https://www.googletagmanager.com/gtag/js”
> Source: SSLConfigGenerator.server_change()
> Revert "use js to replace jquery"

- src/js/state.js
- src/templates/partials/apache.hbs
- src/templates/partials/caddy.hbs
- src/templates/partials/dovecot.hbs
- src/templates/partials/exim.hbs
- src/templates/partials/go.hbs
- src/templates/partials/haproxy.hbs
- src/templates/partials/lighttpd.hbs
- src/templates/partials/nginx.hbs
- src/templates/partials/postfix.hbs
- src/templates/partials/postgresql.hbs
- src/templates/partials/proftpd.hbs
- src/templates/partials/stunnel.hbs
- src/templates/partials/traefik.hbs
config TLSv1.3 key exchange groups where supported
The reason to explicitly configure Groups is due to OpenSSL 3.0 adding ffdhe* groups to the defaults, potentially exposing servers supporting TLSv1.3 and OpenSSL 3.0 to DHEater attacks. (See https://github.com/mozilla/ssl-config-generator/issues/162)
Note: .hbs additions have been made from the documentation and have not been tested on the all the server apps.
Some slight syntax adjustment may turn out to be needed.
Note: This PR exposes the TLS curves that are already defined in the guidelines.  This is not a change to the guidelines.  However, the curves were not previously exposed in ssl-config-generator configs.  This PR implements the Groups/Curves config in server apps that have config support.
> config TLSv1.3 key exchange groups where supported

- config/webpack.config.js
do not use browser-sync in production
load browser-sync-v3-webpack-plugin only when 'npm run watch' (NODE_ENV=development)
load webpack-bundle-analyzer plugin only when 'npm run analyze'
> do not use browser-sync in production

- README.md
- config/webpack.config.js
- package-lock.json
- package.json
- src/js/helpers/apache.js
- src/js/helpers/awsalb.js
- src/js/helpers/haproxy.js
- src/js/helpers/nginx.js
- src/js/helpers/oraclehttp.js
- src/js/state.js
- src/static/guidelines/CHANGELOG.md
remove unused extract-loader dependency
restore clean-webpack-plugin
update README.md
update CHANGELOG.md
output.hstsRedirectCode abstraction (default: 301)
oraclehttp: avoid double-percent-encode in rewrite
> update README.md, CHANGELOG.md, pkg maint

- .github/workflows/deploy-to-production.yml
- package.json
- src/js/index.js
- src/templates/index.ejs
update URL fragment whenever changed
update footer links
update manifest links
use Node v22 in production
> update URL fragment whenever changed, other doc and UX minor updates

- package-lock.json
- src/js/index.js
- src/js/state.js
- src/js/utils.js
- HTML-escape special chars in version strings
- set form.serverName from config data, not from HTML
- set output-config via .innerText, not .innerHTML
> HTML-escape special chars in version strings

- src/js/helpers/haproxy.js
haproxy: ssl-default-server-curves added in 2.9.0
x-ref:
"HAProxy config uses ssl-default-server-curves for versions that do not support it"
https://github.com/mozilla/ssl-config-generator/issues/311
github: fixes #311
> haproxy: ssl-default-server-curves added in 2.9.0

- src/js/analytics.js
- src/static/guidelines/CHANGELOG.md
- src/templates/index.ejs
With the [move to Google Analytics 4][1] this updates the Measurement ID from the old "UA" ID to the new "G" ID. This shouldn't have any impact on the metrics being collected.
Fixes #242
[1]: https://support.google.com/analytics/answer/11583528
> Update Google Analytics ID

- README.md
Add a link to the archive.org captured version of the original generator for historical purposes.
> Add historical link to original generator

- .dockerignore
- Dockerfile
- README.md
All the node dependencies can clutter your local machine, and you may need different versions of node installed.
The Dockerfile was mainly inspired by the official documentation for NodeJS. https://nodejs.org/en/docs/guides/nodejs-docker-webapp/
Please be aware that there are several dependencies which are listed with `npm audit`. I'm not sure how much bandwidth you have for this project, but I'd suggest adding [dependabot](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates) to the project.
> Add support for local development with Docker

- README.md
document how to get release notifications
github: closes #78
> document how to get release notifications

- src/js/helpers/nginx.js
nginx: fix missing semicolon
x-ref:
"Semicolon missing after ssl_dhparam in nginx config"
https://github.com/mozilla/ssl-config-generator/issues/324
github: closes #324
> nginx: fix missing semicolon

- src/js/helpers/go.js
fix syntax error in the generated Go code and ensure newline in HTTP reply
> go: fix unescaped newline in generated string literal

- src/js/helpers/postfix.js
postfix smtpd_tls_chain_files
x-ref:
"Postfix: prefer smtpd_tls_chain_files over smtpd_tls_cert_file and smtpd_tls_key_file"
https://github.com/mozilla/ssl-config-generator/issues/327
github: closes #327
> postfix smtpd_tls_chain_files
