mozilla/ssl-config-generator

- src/templates/index.ejs
Hopefully Fixes #17 
Please try before merging! :)
> Use black bg for window, padding to keep body bg

- src/js/configs.js
- src/templates/partials/dovecot.hbs
> Add support for dovecot

- config/webpack.config.js
- package-lock.json
- package.json
- src/js/index.js
Fix highlight.js for upgrade to 10.x in 040ed45 #128 which had a breaking change
> Update packages and fix highlight.js 10.x upgrade

- src/templates/partials/apache.hbs
> Exclude ACME challenges from being redirected

- src/js/configs.js
- src/templates/partials/lighttpd.hbs
lighttpd 1.4.56
This depends on #120 
Submitting for review.
lighttpd-1.4.56~rc2 is available now, but lighttpd-1.4.56 has not yet been released.
> lighttpd 1.4.56

- src/js/configs.js
> lighttpd update version

- src/js/configs.js
lighttpd 1.4.61 version update
Please also review some simple but older PRs: #137 for Apache and #139 for lighttpd for them to prefer 308 Permanent Redirect to 301 Moved Permanently
Thank you.
> lighttpd 1.4.61 version update

- src/templates/partials/dovecot.hbs
https://doc.dovecot.org/configuration_manual/dovecot_ssl_configuration/#ssl-security-settings
Fixes #156
> Update dovecot DH based on new versions

- README.md
Content from https://github.com/mozilla/ssl-config-generator/issues/23#issuecomment-813822976
Fixes #23
Thanks @gstrauss !
> Add documentation written by gstrauss on template variables

- README.md
- src/static/guidelines/CHANGELOG.md
This summarizes the changes in each version of the JSON recommendations
> Add a CHANGELOG.md for the JSON configurations

- .github/workflows/deploy-to-production.yml
> Fix deploy-to-production artifact action version

- src/js/configs.js
- src/templates/partials/caddy.hbs
Update caddy
github: closes #222
> Fix Caddy 2 configs, drop Caddy 1 support

- src/js/configs.js
- src/templates/partials/postfix.hbs
> postfix: add smtp_tls_*

- src/js/configs.js
- src/js/index.js
- src/templates/index.ejs
initial intro before anything in Server Software has been selected
> initial intro

- package-lock.json
- package.json
- src/css/bs-4.6.2.css
- src/css/index.scss
- src/js/index.js
- src/templates/index.ejs
use bootstrap.native for tooltip for Copy button; preserve bootstrap 4 CSS
> use bootstrap.native for tooltip for Copy button; preserve bootstrap 4 CSS

- src/templates/partials/exim.hbs
exim: tls_eccurve remove quoting
> exim: tls_eccurve remove quoting

- config/webpack.config.js
> remove webpack jquery plugin

- package-lock.json
- package.json
- src/css/index.scss
- src/js/configs.js
- src/js/index.js
remove highlight.js
It properly highlights only some of the configs.
Will its absense be noticed?  If so, we can add it back easily enough.
(The already-selectively-included parts of highlight.js currently added about 130KB (uncompressed) to the page.)
> remove highlight.js

- src/js/helpers/stunnel.js
stunnel: always set sslVersionMin for stunnel 5.50+
> stunnel: always set sslVersionMin for stunnel 5.50+

- src/js/index.js
- src/templates/index.ejs
re-render after navigation (Back and Forward buttons)
> re-render after navigation (Back and Forward buttons)

- config/webpack.config.js
- src/js/index.js
- refactor change_event funcs
reduce some code duplication
- try/catch around webpack git command
return a blank string for git revision if 'git' not available
or 'git' command executed outside a git repository
> refactor change_event funcs

- package-lock.json
- src/js/helpers/nginx.js
nginx: disable stateful ssl_session_cache if TLSv1.3 (https://github.com/mozilla/server-side-tls/issues/282)
nginx: add comment for OCSP stapling config (https://github.com/mozilla/server-side-tls/issues/283)
> nginx: disable stateful ssl_session_cache if TLSv1.3

- src/js/helpers/apache.js
- src/js/helpers/oraclehttp.js
adjust Apache SSLProtocol syntax
x-ref:
https://github.com/mozilla/ssl-config-generator/issues/308
github: fixes #308
> adjust Apache SSLProtocol syntax

- package-lock.json
- src/js/constants.js
- src/js/index.js
- src/js/state.js
- src/static/guidelines/CHANGELOG.md
- src/templates/index.ejs
support site rendering w/ specified guideline vers
x-ref:
"URLs from previously generated configurations no longer show the original configuration"
https://github.com/mozilla/ssl-config-generator/issues/240
> support site rendering w/ specified guideline vers

- src/js/constants.js
Content-Security-Policy: add 'self' to connect-src
x-ref:
https://github.com/mozilla/ssl-config-generator/issues/240
> Content-Security-Policy: add 'self' to connect-src

- README.md
- package-lock.json
- src/js/configs.js
- src/js/helpers/lighttpd.js
- src/js/state.js
> minor updates
